### ISSUE TITLE
what about your dataset?

### ISSUE THREAD

**Issue by wangbing8895** [pyk/hsr#1]
Hi,I am wangbing! A student from China! I have a question about your dataset,could you share your data with us?Thanks!

**Comment by pyk** [comment]
Hi @wangbing8895,

Sorry I can't share my dataset. Btw, you can easily create your own dataset. I use webcam on chrome to collect the training data, you can use my HTML and JS script [here](https://gist.github.com/pyk/48b92225d1e3c5a732d1fda7c7b79ce5).
