### ISSUE TITLE
Jalanin program

### ISSUE THREAD

**Issue by ferrygun** [pyk/hsr#2]
Mas, setelah menjalankan training, bagaimana menjalankan prediksinya? Terima kasih

**Comment by pyk** [comment]
@ferrygun untuk prediksinya tinggal (1) load model yg ada di checkpoint nya lalu (2) jalankan inferensinya pak. 

Contohnya seperti ini:

```python
# Infer the class of one picture
# Usage:
# 1. Update the conf
# 2. Run: python infer.py
import tensorflow as tf
import sys
import os
import time
import numpy

# NOTE: update this
CHECKPOINTS_DIR = 'checkpoints'
META_GRAPH = 'checkpoints/model.meta'
PIC_FILE = 'training-data/3-1-374.png'

if __name__ == '__main__':
    checkpoint_file = tf.train.latest_checkpoint(CHECKPOINTS_DIR)
    saver = tf.train.import_meta_graph(META_GRAPH)
    img_content = tf.read_file(PIC_FILE, 
        name='img_content')
    img_tensor = tf.image.decode_png(img_content, 
        dtype=tf.uint8, channels=3, name='img_decode')

    # Per-image scaling
    img_tensor_std = tf.image.per_image_standardization(img_tensor)
    value = tf.reshape(img_tensor_std, (1, 240, 320, 3))

    # Run the graph
    session = tf.Session()
    saver.restore(session, checkpoint_file)
    result = session.run(value)
    # print result
    probs = session.run(['inference_softmax:0'], feed_dict={'input_image:0': result})
    i = numpy.argmax(probs)
    print 'Predicted:', i + 1
    for d in xrange(5):
        print 'Score class %d : %.3f' % (d+1, probs[0][0][d])
```

**Comment by ferrygun** [comment]
Trims Pak atas informasinya, saya akan coba jalankan, dan bila ada kesulitan saya akan kontak lagi.

**Comment by ferrygun** [comment]
Pak, saya mau tanya lagi tentang ini:

It expect all images inside training-data directory are named using this format: label_id-* where label_id is natural number and 0 < label_id.

Jadi format filenamenya seperti apa contohnya?

**Comment by pyk** [comment]
contohnya ini pak: `1-namafileclass1`, `2-namafileclass2`.

**Comment by ferrygun** [comment]
terima kasih pak, berapa file yang harus saya buat dan download untuk training ?

Dan saya mendapatkan error ini setelah menjalankan program diatas:
TypeError: Cannot interpret feed_dict key as Tensor: The name 'input_image:0' refers to a Tensor which does not exist. The operation, 'input_image', does not exist in the graph.

**Comment by ferrygun** [comment]
Pak, sptnya contoh programnya tidak berjalan, tolong diberikan contoh yang berfungsi pak. terima kasih.

**Comment by pyk** [comment]
@ferrygun itu yg saya kasih cuman contoh aja pak, kurang lebih seperti itu. yang saya jelaskan sebelumnya:

```
@ferrygun untuk prediksinya tinggal (1) load model yg ada di checkpoint nya lalu (2) jalankan inferensinya pak.
```

https://github.com/pyk/hsr/issues/2#issuecomment-279900546
